services:
  postgres:
    image: postgres
    volumes:
      - ./.docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: air_ticket_buyer
    ports:
      - "5432:5432"